version: '3.6'
services:
  keycloak:
    container_name: rems_prod_keycloak  
    # command: ["-Djboss.http.port=8180"]
    ports:
      - '8180:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
      # - KEYCLOAK_IMPORT=/resources/ClientFhirServerRealm.json
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data/
      # - './resources/ClientFhirServerRealm.json:/resources/ClientFhirServerRealm.json'
    image: codexrems/keycloak

  # Create test-ehr container
  test-ehr: # Name of our service
    container_name: rems_prod_test-ehr
    ports: # Port binding to host from docker container
      - '8080:8080' # Bind port 3000 of host to 3000 of container
    image: codexrems/test-ehr
    environment:
      - DOCKER_DEV_PROFILE=true


  # Create crd container
  crd: # Name of our service
    image: codexrems/crd
    container_name: rems_prod_crd
    ports: # Port binding to host from docker container
      - "8090:8090" # Bind port 3000 of host to 3000 of container
    environment:
      VSAC_API_KEY: ${VSAC_API_KEY}


  # Create crd request generator container
  crd-request-generator: # Name of our service
    image: codexrems/crd-request-generator
    container_name: rems_prod_crd-request-generator
    environment:
      - REACT_APP_REMS_CONFIG=true
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
      - "3001:3001"


  # Create dtr container
  dtr: # Name of our service
    image: codexrems/dtr    
    container_name: rems_prod_dtr
    ports: # Port binding to host from docker container
      - "3005:3005" # Bind port 3000 of host to 3000 of container

  # # Create rems container
  rems: # Name of our service
    image: codexrems/rems
    container_name: rems_prod_rems
    ports: # Port binding to host from docker container
      - "9015:9015" # Bind port 3000 of host to 3000 of container



volumes:
  keycloak-data:
